#
# .bash_aliases
#
alias ..='cd ..'
alias .4='cd ../../../../'
alias allspice='ssh allspice.cs.swarthmore.edu'
alias c='/usr/bin/clear'
alias cslab='ssh -p 9000 cslab.cs.swarthmore.edu'
alias d='date +"%n%t%D %a%n%t%r%n"'
alias diff='colordiff'
alias f='finger'
alias gde='ssh goofydogears.net'
alias h='history'
alias jk='ssh -X jk@fennel.cs.swarthmore.edu'
alias z='ssh-agent zsh'
alias k='gitkey ; ssh-add '
alias l.='ls -d .* --color=auto'
alias la='ls -a'
alias lal='ls -al'
alias land='enscript -2rhGj'
alias lcap='ls [A-Z]*'
alias less='less -M'
alias ll='ls -l'
alias lnew='ls -alt | head -16'
alias lrt='ls -alrt | head -16'
alias ls='ls -CF'
alias lynx='lynx -cfg=~/.lynxcfg'
alias m='less -M'
alias ml='last -2000 | grep -v root | head -20'
alias more='less -M'
alias nd="date +'%Y-%m-%d--%H:%M:%S:%N'"
alias nver='cat /proc/driver/nvidia/version'
alias psn='ps -ef | grep -v root | grep -v smtp | grep -v knerr'
alias psv='ps -ef | grep -v root'
alias r='resize'
alias rm='rm -i'
alias snt='mutt -f ~/mdir/sent'
alias spd='sudo postsuper -d '
alias sti='sudo tripwire --check --interactive'
alias su='su -m'
alias tmesg='sudo dmesg -T | tail -15'
alias whatami='cat /etc/lsb-release'
alias chop='PRINTER=machop; export PRINTER'
alias dice='PRINTER=TheDicer; export PRINTER'
alias grate='PRINTER=TheGrater; export PRINTER'
alias mince='PRINTER=TheMincer; export PRINTER'
alias shred='PRINTER=TheShredder; export PRINTER'
alias slice='PRINTER=TheSlicer; export PRINTER'
