#! /bin/bash

# install the dot files

export PATH=/bin:/sbin:/usr/bin:/usr/local/bin:/usr/sbin

echo "installing dotfiles...."

# make it idempotent!!!

# ask y/n question, return true/false
askyn () {
  question=$1
  echo "$question"
  read -r -p "[y/n] " response
  if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]] ; then
    return 0   # true
  else
    return 1   # false
  fi
}

# function to ask: replace [y/n]? 
# make a backup copy???
cprpl () {
  src=$1
  dst=$2
  if [ -e $dst ] ; then
    if askyn "$dst already exists...replace it?";
    then
      rm -f $dst     # note: dst needs to be full path, not just dir/.
      cp $src $dst
    else
      echo "ok...leaving $dst as is..."
    fi
  else
    cp $src $dst
  fi 
}

stuff="curl zsh zsh-syntax-highlighting tmux screen rsync "\
"git vim mutt enscript"
echo "============================================="
echo "stuff you probably want installed:"
echo $stuff
echo "============================================="
if askyn "run sudo apt-get install?";
then
  sudo apt-get install $stuff
fi
echo "============================================="
echo "you also might want i3 ssh-askpass..."
if askyn "run sudo apt-get install i3 ssh-askpass?";
then
  sudo apt-get install i3 ssh-askpass
fi
echo "============================================="

# bash
echo "============================================="
cprpl bash_aliases ~/.bash_aliases

# check if ~/.oh-my-zsh already exists...
echo "============================================="
if [ ! -e ${HOME}/.oh-my-zsh ] ; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi
echo "============================================="
cprpl zshrc ~/.zshrc
if [ ! -e ${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions ] ; then
  git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
fi
echo "============================================="
cprpl jkblinks.zsh-theme ~/.oh-my-zsh/themes/jkblinks.zsh-theme
if [ ${SHELL} != "/usr/bin/zsh" ] ; then
  echo "changing shell to zsh..."
  chsh -s /usr/bin/zsh
fi

# python
echo "============================================="
cprpl pythonrc ~/.pythonrc

# mutt
if [ ! -e ${HOME}/mdir/tmp ] ; then
  mkdir -p ~/mdir/tmp
fi
echo "============================================="
cprpl muttrc ~/.muttrc

# ssh auth keys file
if [ ! -e ${HOME}/.ssh ] ; then
  mkdir ${HOME}/.ssh
fi
echo "============================================="
cprpl authorized_keys ${HOME}/.ssh/authorized_keys

# vimrc, vim-plug
echo "============================================="
cprpl vimrc ~/.vimrc
echo "might have to run :PlugInstall to get all the vim plugins"

# tmux.conf
echo "============================================="
cprpl tmux.conf ~/.tmux.conf

echo ""
echo "---- all done! ----"
echo ""
